/** generation -> versionGroup -> version */
export const enum Version {
  Red = 'red',
  Blue = 'blue',
  Yellow = 'yellow',
  Gold = 'gold',
  Silver = 'silver',
  Crystal = 'crystal',
  Ruby = 'ruby',
  Sapphire = 'sapphire',
  Emerald = 'emerald',
  FireRed = 'firered',
  LeafGreen = 'leafgreen',
  Diamond = 'diamond',
  Pearl = 'Pearl',
  Platinum = 'platinum',
  HeartGold = 'heartgold',
  SoulSilver = 'heartsilver',
  Black = 'black',
  White = 'white',
  Black2 = 'black-2',
  White2 = 'white-2',
  X = 'x',
  Y = 'y',
  OmegaRuby = 'omega-ruby',
  AlphaSapphire = 'alpha-sapphire',
  Sun = 'sun',
  Moon = 'moon',
  UltraSun = 'ultra-sun',
  UltraMoon = 'ultra-moon',
  Sword = 'sword',
  Shield = 'shield',
}